### ISSUE TITLE
How does it works?

### ISSUE THREAD

**Issue by EdsonCol** [nextgis/gnm_qgis#3]
I just can't use it and don't find info.

**Comment by MikhanGusev** [comment]
The plugin requires that QGIS is built with GDAL 2.1 (or later) in which GNM is turned on. Currently GNM in GDAL 2.1 is turned off. You could do the following:
1) Use custom QGIS/GDAL builds;
2) Use NextGIS QGIS where this plugin already works fine; http://nextgis.com/nextgis-qgis
3) Wait for nearest QGIS/GDAL releases where GNM will be enabled by default (currently is being discussed).
